version: '3.4'
services:

  # https://medium.com/opentracing/take-opentracing-for-a-hotrod-ride-f6e3141f7941
  hotrod:
    image: jaegertracing/example-hotrod:1.60@sha256:d8d31e769e054bd66f93398f66200ae2ecbe2120549fbc29c42d0de743c74e9e
    ports:
      - 8080-8083:8080-8083
    environment:
      - JAEGER_AGENT_HOST=grafana-agent
      - JAEGER_AGENT_PORT=16831
      #- JAEGER_AGENT_HOST=jaeger
      #- JAEGER_AGENT_PORT=6831
      #- JAEGER_SAMPLER_TYPE=remote
      #- JAEGER_SAMPLING_ENDPOINT=http://jaeger:6381/sampling
      #- JAEGER_AGENT_HOST=otel-collector
      #- JAEGER_AGENT_PORT=36831
    #command: ["--agent.tags=span_type=grafana", --reporter.grpc.host-port=grafana-agent:16831"]

  # https://grafana.com/docs/agent/latest/configuration/traces-config/
  grafana-agent:
    image: grafana/agent:latest
    ports:
      - "12347:12345"
      - "12348:12348"
      - "16685:16685"
      - "16831:16831"
      - "55679:55679"
    volumes:
      - "./configured-grafana-agent-config.yaml:/etc/agent/agent.yaml"
    command: [ "-config.file=/etc/agent/agent.yaml" ]

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - 6831:6831
      - "26831:6831"
      - "16686:16686"

  # https://grafana.com/blog/2021/04/13/how-to-send-traces-to-grafana-clouds-tempo-service-with-opentelemetry-collector/
  otel-collector:
    image: otel/opentelemetry-collector:latest
    ports:
      - "36831:36831"
    command: "--config /etc/otel-config.yaml"
    volumes:
      - ./otel-config.yaml:/etc/otel-config.yaml