version: "3.8"
volumes:
  grafana:
  postgres:

services:

  # Grafana for exploring and visualizing data
  grafana-server-1:
    image: grafana/grafana:10.4.19@sha256:a9043254ba16fb10945cc27333963dfd08eccbb43b51f1222d831cc564e3a1f4
    #image: grafana/grafana:latest
    #image: grafana/grafana:9.0.6-ubuntu
    #image: grafana/grafana:latest
    #image: grafana/grafana:8.2.1
    #image: grafana/grafana:8.5.6
    #restart: always
    volumes:
      - "./grafana/grafana.ini:/etc/grafana/grafana.ini"
      - "./grafana/provisioning:/etc/grafana/provisioning"
    ports:
      - "3001:3000"

  # Grafana for exploring and visualizing data
  grafana-server-2:
    image: grafana/grafana:9.5.21@sha256:ec106c7d446c88377f9d6c4cd363361b5846c361a28f5669d1b5e92926d94891
    #image: grafana/grafana:latest
    #image: grafana/grafana:9.0.6-ubuntu
    #image: grafana/grafana:latest
    #image: grafana/grafana:8.2.1
    #image: grafana/grafana:8.5.6
    #restart: always
    volumes:
      - "./grafana/grafana.ini:/etc/grafana/grafana.ini"
      - "./grafana/provisioning:/etc/grafana/provisioning"
    ports:
      - "3002:3000" 
 
  # Grafana for exploring and visualizing data
  grafana-server-3:
    image: grafana/grafana:8.5.27@sha256:b43abed8a2b8c5a4055c3729d77ae11c9646c4b9feefb5c136b7c67dcdad21c0
    #image: grafana/grafana:latest
    #image: grafana/grafana:9.0.6-ubuntu
    #image: grafana/grafana:latest
    #image: grafana/grafana:8.2.1
    #image: grafana/grafana:8.5.6
    #restart: always
    volumes:
      - "./grafana/grafana.ini:/etc/grafana/grafana.ini"
      - "./grafana/provisioning:/etc/grafana/provisioning"
    ports:
      - "3003:3000"


  # Grafana for exploring and visualizing data
  grafana-server-4:
    image: grafana/grafana:8.5.27@sha256:b43abed8a2b8c5a4055c3729d77ae11c9646c4b9feefb5c136b7c67dcdad21c0
    #image: grafana/grafana:latest
    #image: grafana/grafana:9.0.6-ubuntu
    #image: grafana/grafana:latest
    #image: grafana/grafana:8.2.1
    #image: grafana/grafana:8.5.6
    #restart: always
    volumes:
      - "./grafana/grafana.ini:/etc/grafana/grafana.ini"
      - "./grafana/provisioning:/etc/grafana/provisioning"
    ports:
      - "3004:3000"

    # Grafana for exploring and visualizing data
  grafana-server-5:
    image: grafana/grafana:7.5.17@sha256:15abb652aa82eeb9f45589278b34ae6ef0e96f74c389cadde31831eb0b1ce228
    #image: grafana/grafana:latest
    #image: grafana/grafana:9.0.6-ubuntu
    #image: grafana/grafana:latest
    #image: grafana/grafana:8.2.1
    #image: grafana/grafana:8.5.6
    #restart: always
    volumes:
      - "./grafana/grafana.ini:/etc/grafana/grafana.ini"
      - "./grafana/provisioning:/etc/grafana/provisioning"
    ports:
      - "3005:3000"

   # Grafana Metrics
  mimir:
    image: grafana/mimir:latest
    depends_on:
      - grafana-server-1
      - grafana-server-2
      - grafana-server-3
    volumes:
      - "./mimir/config-single.yaml:/etc/mimir/config.yaml"
    ports:
      - "9009:9009"
    command: [
      "-config.file=/etc/mimir/config.yaml"
    ]

  # Grafana Agent
  grafana-agent:
    image: grafana/agent:latest
    depends_on:
      - mimir
    ports:
      - "12345:12345"
      - "3500:3500"
      - "16603:16603"
    volumes:
      - "./grafana-agent/config.yaml:/etc/agent/agent.yaml"
    command: [
      "-config.file=/etc/agent/agent.yaml",
      "-server.http.address=0.0.0.0:12345",
    ]