version: "2.1"

services:
  # Grafana agent
  # grafana-agent:
  #   image: grafana/agent:latest
  #   hostname: grafana-agent
  #   ports:
  #     - "12347:12345"
  #     - "12348:12348"
  #     - "6832:6832"
  #     - "55679:55679"
  #   volumes:
  #     - "${PWD}/configured/grafana-agent-config.yaml:/etc/agent/agent.yaml"
  #   command: [
  #     "-config.file=/etc/agent/agent.yaml",
  #     "-enable-features=integrations-next",
  #     "-server.http.address=0.0.0.0:12345",
  #   ]

  grafana-alloy:
    image: grafana/alloy:latest@sha256:8abcd0d97a97099cabb34be8dcfc448fca6c35931ae9291aaf74056105dedcca
    ports:
      - "12347:12345"
      - "12348:12348"
      - "6832:6832"
      - "55679:55679"
    volumes:
      - "${PWD}/configured/grafana-alloy.river:/etc/alloy/config.alloy"
    command: [
        "run",
        "--server.http.listen-addr=0.0.0.0:12345",
        "--stability.level=experimental",
        "/etc/alloy/config.alloy",
              ]   
  # vsphere Simulator  
  # docker run --rm -d -p 443:443/tcp nimmis/vcsim:latest
  vcsimulator:
    image: nimmis/vcsim:latest@sha256:99c2b330ab4f18c1b7816a6ce34b25f4738cd598c2dd4745d3f742be731bd3ed
    hostname: vcsimulator
    restart: always
    ports:
      - "443:443"

  # vsphere powercorecli  
  # docker run --rm -it --net=host vmware/powerclicore
  # Set-PowerCLIConfiguration -InvalidCertificateAction ignore -confirm:$false
  # Connect-VIServer -Server vcsimulator -Port 443 -User u -Password p
  # Get-VM
  vcpowerclicore:
    image: vmware/powerclicore@sha256:5d13398ec75c0c3858f2f68a598db4368f4c22a98d0d67ce926b181e420778d3
    hostname: vcpowerclicore
    entrypoint: [ "sleep", "86400" ]
    #network_mode: "host"
    #restart: always
    #command: [ "/opt/microsoft/powershell/7-lts/pwsh" ]