version: "3.8"

services:

  # Grafana for exploring and visualizing data
  grafana-server:
    image: grafana/grafana-enterprise:latest-ubuntu@sha256:ff80aec107ee6bca728a29df3b52e6ccd958dd1841d001ae95f7e866b885bd69
    #image: grafana-enterprise:main-ubuntu
    #image: grafana/grafana:9.0.6-ubuntu
    #image: grafana/grafana:latest
    #image: grafana/grafana:8.2.1
    #image: grafana/grafana:8.5.6
    #depends_on:
    #  - clickhouse-server
    #restart: always
    volumes:
      - "./grafana/grafana.ini:/etc/grafana/grafana.ini"
      - "./configured-index.html:/usr/share/grafana/public/views/index.html"
      #- "./index-template.html:/usr/share/grafana/public/views/index-template.html"
      #- "./grafana/provisioning:/etc/grafana/provisioning"
      #- "./grafana/provisioning/dashboards:/var/lib/grafana/dashboards"
      #- "/tmp/container-tmp:/tmp/container-tmp"
    ports:
      - "3000:3000"
    environment:
      - GF_FEATURE_TOGGLES_ENABLE=tempoSearch,tempoServiceGraph
      - GF_INSTALL_PLUGINS=grafana-clickhouse-datasource
    labels:
      namespace: grafana
    #logging: *default-logging
